# Generated by Django 2.2.7 on 2019-11-24 02:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareablelink',
            name='encryption_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='shareablelink',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
    ]
