# Generated by Django 2.2.7 on 2019-11-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20191124_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareablelink',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
