# Generated by Django 2.2.7 on 2019-11-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_shareablelink_iv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shareablelink',
            old_name='iv',
            new_name='original_text',
        ),
        migrations.RemoveField(
            model_name='shareablelink',
            name='text',
        ),
        migrations.AddField(
            model_name='shareablelink',
            name='encrypted_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
