# Generated by Django 2.2.7 on 2019-11-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_auto_20191124_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareablelink',
            name='encrypted_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
